upload test results #4

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -13,21 +13,28 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v2            # checkout the repo
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
+        
     - name: Build with Maven
-      run: mvn test --file pom.xml
+      run: mvn test --file pom.xml         # run maven tests
 
-    - uses: actions/upload-artifact@v3
-      if: success() || failure()
+    - name: Download a Build Artifact
+    - uses: actions/upload-artifact@v3     # upload test results
+      if: success() || failure()           # run this step even if previous step failed
       with:
         name: test result
         files: "target/surefire-reports/*.xml"
         path: |
           target/surefire-reports/
           allure-results/*
+          
+    - name: Publish Unit Test Results
+      uses: EnricoMi/publish-unit-test-result-action@v1
+      with:
+        files: "target/surefire-reports/*.xml"
